package com.organism.app;

import android.content.*;
import android.database.Cursor;
import android.database.sqlite.*;
import java.text.SimpleDateFormat;
import java.util.*;

public class Db extends SQLiteOpenHelper {
    private static final int VERSION=2;
    private final Context ctx;
    public Db(Context c){super(c,"organism.db",null,VERSION);ctx=c;}
    @Override public void onConfigure(SQLiteDatabase d){d.setForeignKeyConstraintsEnabled(true);d.execSQL("PRAGMA journal_mode=WAL");d.execSQL("PRAGMA busy_timeout=5000");}
    @Override public void onCreate(SQLiteDatabase d){schema(d);seed(d);}
    @Override public void onUpgrade(SQLiteDatabase d,int o,int n){schema(d);migrateLegacy(d);}
    private void schema(SQLiteDatabase d){
        d.execSQL("CREATE TABLE IF NOT EXISTS projects(id INTEGER PRIMARY KEY AUTOINCREMENT,logical_id TEXT UNIQUE NOT NULL,name TEXT NOT NULL,description TEXT,status TEXT NOT NULL DEFAULT 'ACTIVE',created_at TEXT NOT NULL,updated_at TEXT NOT NULL)");
        d.execSQL("CREATE TABLE IF NOT EXISTS project_states(id INTEGER PRIMARY KEY AUTOINCREMENT,logical_id TEXT UNIQUE NOT NULL,project_id INTEGER REFERENCES projects(id),version INTEGER NOT NULL DEFAULT 1,branch TEXT,summary TEXT,is_current INTEGER NOT NULL DEFAULT 1,created_at TEXT NOT NULL)");
        d.execSQL("CREATE TABLE IF NOT EXISTS tasks(id INTEGER PRIMARY KEY AUTOINCREMENT,logical_id TEXT UNIQUE NOT NULL,project_id INTEGER REFERENCES projects(id),state_id INTEGER REFERENCES project_states(id),parent_task_id INTEGER REFERENCES tasks(id),title TEXT NOT NULL,description TEXT,status TEXT NOT NULL DEFAULT 'OPEN',priority INTEGER DEFAULT 0,started_at TEXT,completed_at TEXT,completion_confirmed_by TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL)");
        d.execSQL("CREATE TABLE IF NOT EXISTS sources(id INTEGER PRIMARY KEY AUTOINCREMENT,logical_id TEXT UNIQUE NOT NULL,source_type TEXT NOT NULL,source_name TEXT NOT NULL,source_path TEXT,external_id TEXT,checksum TEXT,parent_source_id INTEGER REFERENCES sources(id),raw_text TEXT,created_at TEXT NOT NULL)");
        d.execSQL("CREATE TABLE IF NOT EXISTS events(id INTEGER PRIMARY KEY AUTOINCREMENT,logical_id TEXT UNIQUE NOT NULL,project_id INTEGER REFERENCES projects(id),state_id INTEGER REFERENCES project_states(id),task_id INTEGER REFERENCES tasks(id),kind TEXT NOT NULL,description TEXT NOT NULL,claim_status TEXT DEFAULT 'STATED',verification_status TEXT DEFAULT 'NOT_VERIFIED',causality TEXT,source_id INTEGER REFERENCES sources(id),occurred_at TEXT NOT NULL,created_at TEXT NOT NULL)");
        d.execSQL("CREATE TABLE IF NOT EXISTS actions(id INTEGER PRIMARY KEY AUTOINCREMENT,logical_id TEXT UNIQUE NOT NULL,event_id INTEGER REFERENCES events(id),action_type TEXT NOT NULL,description TEXT NOT NULL,created_at TEXT NOT NULL)");
        d.execSQL("CREATE TABLE IF NOT EXISTS results(id INTEGER PRIMARY KEY AUTOINCREMENT,logical_id TEXT UNIQUE NOT NULL,action_id INTEGER REFERENCES actions(id),status TEXT NOT NULL,description TEXT NOT NULL,created_at TEXT NOT NULL)");
        d.execSQL("CREATE TABLE IF NOT EXISTS verifications(id INTEGER PRIMARY KEY AUTOINCREMENT,logical_id TEXT UNIQUE NOT NULL,result_id INTEGER REFERENCES results(id),status TEXT NOT NULL,method TEXT,evidence TEXT,created_at TEXT NOT NULL)");
        d.execSQL("CREATE TABLE IF NOT EXISTS memory_objects(id INTEGER PRIMARY KEY AUTOINCREMENT,logical_id TEXT UNIQUE NOT NULL,kind TEXT NOT NULL,title TEXT NOT NULL,content TEXT NOT NULL,project_id INTEGER REFERENCES projects(id),state_id INTEGER REFERENCES project_states(id),task_id INTEGER REFERENCES tasks(id),source_id INTEGER REFERENCES sources(id),claim_status TEXT DEFAULT 'STATED',verification_status TEXT DEFAULT 'NOT_VERIFIED',confidence REAL DEFAULT .5,priority INTEGER DEFAULT 0,availability_level TEXT DEFAULT 'ACTIVE',memory_status TEXT DEFAULT 'ACTIVE',is_protected INTEGER DEFAULT 0,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,last_accessed_at TEXT NOT NULL)");
        d.execSQL("CREATE VIRTUAL TABLE IF NOT EXISTS memory_fts USING fts5(logical_id UNINDEXED,title,content,content='memory_objects',content_rowid='id')");
        d.execSQL("CREATE TRIGGER IF NOT EXISTS memory_ai AFTER INSERT ON memory_objects BEGIN INSERT INTO memory_fts(rowid,logical_id,title,content) VALUES(new.id,new.logical_id,new.title,new.content);END");
        d.execSQL("CREATE TRIGGER IF NOT EXISTS memory_ad AFTER DELETE ON memory_objects BEGIN INSERT INTO memory_fts(memory_fts,rowid,logical_id,title,content) VALUES('delete',old.id,old.logical_id,old.title,old.content);END");
        d.execSQL("CREATE TRIGGER IF NOT EXISTS memory_au AFTER UPDATE ON memory_objects BEGIN INSERT INTO memory_fts(memory_fts,rowid,logical_id,title,content) VALUES('delete',old.id,old.logical_id,old.title,old.content);INSERT INTO memory_fts(rowid,logical_id,title,content) VALUES(new.id,new.logical_id,new.title,new.content);END");
        d.execSQL("CREATE TABLE IF NOT EXISTS memory_tags(id INTEGER PRIMARY KEY AUTOINCREMENT,memory_id INTEGER REFERENCES memory_objects(id),dimension TEXT,value TEXT,normalized_value TEXT,confidence REAL DEFAULT .5,source_id INTEGER REFERENCES sources(id),created_at TEXT)");
        d.execSQL("CREATE TABLE IF NOT EXISTS relations(id INTEGER PRIMARY KEY AUTOINCREMENT,logical_id TEXT UNIQUE NOT NULL,from_object_id INTEGER REFERENCES memory_objects(id),to_object_id INTEGER REFERENCES memory_objects(id),relation_type TEXT,weight REAL DEFAULT 1,confidence REAL DEFAULT .5,source_id INTEGER REFERENCES sources(id),created_at TEXT)");
        d.execSQL("CREATE TABLE IF NOT EXISTS experiences(id INTEGER PRIMARY KEY AUTOINCREMENT,logical_id TEXT UNIQUE NOT NULL,project_id INTEGER REFERENCES projects(id),task_id INTEGER REFERENCES tasks(id),what_happened TEXT,what_was_tried TEXT,what_worked TEXT,what_failed TEXT,understanding_before TEXT,understanding_after TEXT,confidence REAL DEFAULT .5,experience_type TEXT DEFAULT 'NEUTRAL',applicability_json TEXT,created_at TEXT,updated_at TEXT)");
        d.execSQL("CREATE TABLE IF NOT EXISTS rejected_paths(id INTEGER PRIMARY KEY AUTOINCREMENT,logical_id TEXT UNIQUE NOT NULL,project_id INTEGER REFERENCES projects(id),task_id INTEGER REFERENCES tasks(id),description TEXT,reason TEXT,source_id INTEGER REFERENCES sources(id),created_at TEXT)");
        d.execSQL("CREATE TABLE IF NOT EXISTS loss_coverage(id INTEGER PRIMARY KEY AUTOINCREMENT,logical_id TEXT UNIQUE NOT NULL,project_id INTEGER REFERENCES projects(id),item_type TEXT,description TEXT,affected_area TEXT,source_id INTEGER REFERENCES sources(id),created_at TEXT)");
        d.execSQL("CREATE TABLE IF NOT EXISTS sessions(id INTEGER PRIMARY KEY AUTOINCREMENT,logical_id TEXT UNIQUE NOT NULL,device_id TEXT,interface_type TEXT,project_id INTEGER REFERENCES projects(id),task_id INTEGER REFERENCES tasks(id),started_at TEXT,ended_at TEXT,last_activity_at TEXT)");
        d.execSQL("CREATE TABLE IF NOT EXISTS availability_log(id INTEGER PRIMARY KEY AUTOINCREMENT,memory_id INTEGER REFERENCES memory_objects(id),accessed_by TEXT,access_type TEXT,created_at TEXT)");
        d.execSQL("CREATE TABLE IF NOT EXISTS change_log(id INTEGER PRIMARY KEY AUTOINCREMENT,object_type TEXT,object_id INTEGER,field_name TEXT,old_value TEXT,new_value TEXT,changed_by TEXT,reason TEXT,created_at TEXT)");
        d.execSQL("CREATE TABLE IF NOT EXISTS system_params(key TEXT PRIMARY KEY,value TEXT,updated_at TEXT)");
        d.execSQL("CREATE INDEX IF NOT EXISTS idx_mem_ctx ON memory_objects(project_id,task_id,state_id,memory_status,availability_level)");
        d.execSQL("CREATE INDEX IF NOT EXISTS idx_rel_from ON relations(from_object_id)");
        d.execSQL("CREATE INDEX IF NOT EXISTS idx_rel_to ON relations(to_object_id)");
    }
    private void migrateLegacy(SQLiteDatabase d){try{Cursor c=d.rawQuery("SELECT role,text FROM messages ORDER BY id ASC",null);while(c.moveToNext())event(c.getString(0).equals("user")?"USER_MESSAGE":"MODEL_OUTPUT",c.getString(1),project("ORGANISM"),0,0,"STATED","NOT_VERIFIED");c.close();}catch(Exception ignored){}try{Cursor c=d.rawQuery("SELECT title,content FROM memories ORDER BY id ASC",null);while(c.moveToNext())memory("NOTE",c.getString(0),c.getString(1),project("ORGANISM"),0,0,"STATED","NOT_VERIFIED",0.5);c.close();}catch(Exception ignored){}try{Cursor c=d.rawQuery("SELECT happened,tried,worked,confidence FROM experiences ORDER BY id ASC",null);while(c.moveToNext())experience(c.getString(0),c.getString(1),c.getString(2),"",project("ORGANISM"),c.getDouble(3),"NEUTRAL","{\"migrated\":true}");c.close();}catch(Exception ignored){}}\n    private void seed(SQLiteDatabase d){String n=now();d.execSQL("INSERT OR IGNORE INTO system_params(key,value,updated_at) VALUES('schema_version','0.3',?)",new Object[]{n});if(queryOne("SELECT id FROM projects WHERE logical_id='PRJ-ORGANISM'",null)==null){ContentValues p=v();p.put("logical_id","PRJ-ORGANISM");p.put("name","ORGANISM");p.put("description","Непрерывный агент");p.put("created_at",n);p.put("updated_at",n);long id=d.insert("projects",null,p);ContentValues s=v();s.put("logical_id","PST-ORGANISM-001");s.put("project_id",id);s.put("branch","main");s.put("summary","Базовое состояние ORGANISM");s.put("created_at",n);d.insert("project_states",null,s);}}
    private ContentValues v(){return new ContentValues();}
    public String now(){return new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSSXXX",Locale.US).format(new Date());}
    public String id(String p){return p+"-"+UUID.randomUUID().toString().substring(0,8).toUpperCase(Locale.US);}
    public Cursor query(String s,String[] a){return getReadableDatabase().rawQuery(s,a);}
    public String queryOne(String s,String[] a){Cursor c=query(s,a);try{return c.moveToFirst()?c.getString(0):null;}finally{c.close();}}
    public int count(String t){Cursor c=query("SELECT COUNT(*) FROM "+t,null);try{c.moveToFirst();return c.getInt(0);}finally{c.close();}}
    public long project(String name){String q=queryOne("SELECT id FROM projects WHERE name=?",new String[]{name});if(q!=null)return Long.parseLong(q);ContentValues v=v();v.put("logical_id",id("PRJ"));v.put("name",name);v.put("status","ACTIVE");v.put("created_at",now());v.put("updated_at",now());return getWritableDatabase().insert("projects",null,v);}
    public long state(long p){String q=queryOne("SELECT id FROM project_states WHERE project_id=? AND is_current=1 ORDER BY id DESC LIMIT 1",new String[]{""+p});return q==null?0:Long.parseLong(q);}
    public long source(String type,String name,String path,String raw,String checksum){ContentValues v=v();v.put("logical_id",id("SRC"));v.put("source_type",type);v.put("source_name",name);v.put("source_path",path);v.put("raw_text",raw);v.put("checksum",checksum);v.put("created_at",now());return getWritableDatabase().insert("sources",null,v);}
    public long event(String kind,String desc,long p,long task,long src,String claim,String verify){ContentValues v=v();v.put("logical_id",id("EVT"));v.put("project_id",p>0?p:null);v.put("state_id",state(p)>0?state(p):null);v.put("task_id",task>0?task:null);v.put("kind",kind);v.put("description",desc);v.put("claim_status",claim);v.put("verification_status",verify);v.put("source_id",src>0?src:null);v.put("occurred_at",now());v.put("created_at",now());return getWritableDatabase().insert("events",null,v);}
    public long memory(String kind,String title,String content,long p,long task,long src,String claim,String verify,double conf){String n=now();ContentValues v=v();v.put("logical_id",id("MEM"));v.put("kind",kind);v.put("title",title);v.put("content",content);v.put("project_id",p>0?p:null);v.put("state_id",state(p)>0?state(p):null);v.put("task_id",task>0?task:null);v.put("source_id",src>0?src:null);v.put("claim_status",claim);v.put("verification_status",verify);v.put("confidence",conf);v.put("created_at",n);v.put("updated_at",n);v.put("last_accessed_at",n);return getWritableDatabase().insert("memory_objects",null,v);}
    public void relation(long a,long b,String type,long src){ContentValues v=v();v.put("logical_id",id("REL"));v.put("from_object_id",a);v.put("to_object_id",b);v.put("relation_type",type);v.put("source_id",src>0?src:null);v.put("created_at",now());getWritableDatabase().insert("relations",null,v);}
    public long experience(String happened,String tried,String worked,String failed,long p,double conf,String type,String app){ContentValues v=v();v.put("logical_id",id("EXP"));v.put("project_id",p);v.put("what_happened",happened);v.put("what_was_tried",tried);v.put("what_worked",worked);v.put("what_failed",failed);v.put("confidence",conf);v.put("experience_type",type);v.put("applicability_json",app);v.put("created_at",now());v.put("updated_at",now());return getWritableDatabase().insert("experiences",null,v);}
    public String context(String q){StringBuilder b=new StringBuilder("PROJECT: ORGANISM\n");b.append("STATE: ").append(queryOne("SELECT summary FROM project_states WHERE is_current=1 ORDER BY id DESC LIMIT 1",null)).append("\n\n");Cursor t=query("SELECT logical_id,title,status,description FROM tasks WHERE status IN ('OPEN','IN_PROGRESS','WAITING') ORDER BY priority DESC,updated_at DESC LIMIT 12",null);b.append("ACTIVE TASKS:\n");while(t.moveToNext())b.append("- ").append(t.getString(0)).append(" ").append(t.getString(1)).append(" [").append(t.getString(2)).append("] ").append(t.getString(3)).append("\n");t.close();Cursor m=query("SELECT logical_id,title,content,claim_status,verification_status,confidence FROM memory_objects WHERE memory_status='ACTIVE' AND availability_level!='DELETED' ORDER BY priority DESC,last_accessed_at DESC LIMIT 18",null);b.append("\nMEMORY:\n");while(m.moveToNext())b.append("- ").append(m.getString(0)).append(" ").append(m.getString(1)).append(" [").append(m.getString(3)).append("/").append(m.getString(4)).append(",conf=").append(m.getDouble(5)).append("] ").append(m.getString(2)).append("\n");m.close();try{if(q!=null&&!q.trim().isEmpty()){Cursor f=query("SELECT m.logical_id,m.title,m.content,m.confidence FROM memory_fts f JOIN memory_objects m ON m.id=f.rowid WHERE memory_fts MATCH ? ORDER BY bm25(memory_fts) LIMIT 12",new String[]{fts(q)});b.append("\nFTS:\n");while(f.moveToNext())b.append("- ").append(f.getString(0)).append(" ").append(f.getString(1)).append(" [").append(f.getDouble(3)).append("] ").append(f.getString(2)).append("\n");f.close();}}catch(Exception ignored){}Cursor e=query("SELECT logical_id,what_happened,what_was_tried,what_worked,what_failed,confidence,applicability_json FROM experiences ORDER BY updated_at DESC LIMIT 10",null);b.append("\nEXPERIENCE (CONDITIONAL):\n");while(e.moveToNext())b.append("- ").append(e.getString(0)).append(" conf=").append(e.getDouble(5)).append(" app=").append(e.getString(6)).append("\n  ").append(e.getString(1)).append("\n  tried=").append(e.getString(2)).append("\n  worked=").append(e.getString(3)).append("\n  failed=").append(e.getString(4)).append("\n");e.close();return b.toString();}
    private String fts(String q){return q.replaceAll("[^\\p{L}\\p{N} ]"," ").trim().replaceAll("\\s+"," OR ");}
    public void reinforceExperience(long experienceId,boolean confirmed,String reason){
        SQLiteDatabase w=getWritableDatabase();
        Cursor cur=w.rawQuery("SELECT confidence,experience_type FROM experiences WHERE id=?",new String[]{""+experienceId});
        if(!cur.moveToFirst()){cur.close();return;}
        double old=cur.getDouble(0);String oldType=cur.getString(1);cur.close();
        double next=confirmed?Math.min(1.0,old+.10):Math.max(0.0,old-.20);
        String type=confirmed?(oldType.equals("NEGATIVE")?"NEGATIVE":"POSITIVE"):(oldType.equals("POSITIVE")?"MIXED":"NEGATIVE");
        ContentValues v=new ContentValues();v.put("confidence",next);v.put("experience_type",type);v.put("updated_at",now());
        w.update("experiences",v,"id=?",new String[]{""+experienceId});
        ContentValues log=new ContentValues();log.put("object_type","EXPERIENCE");log.put("object_id",experienceId);log.put("field_name","confidence");log.put("old_value",""+old);log.put("new_value",""+next);log.put("changed_by","ORGANISM");log.put("reason",reason==null?"":reason);log.put("created_at",now());w.insert("change_log",null,log);
        if(!confirmed){
            ContentValues rp=new ContentValues();rp.put("logical_id",id("RJP"));rp.put("project_id",queryOne("SELECT project_id FROM experiences WHERE id=?",new String[]{""+experienceId}));rp.put("description","Опыт refuted: "+experienceId);rp.put("reason",reason==null?"":reason);rp.put("created_at",now());w.insert("rejected_paths",null,rp);
        }
    }

    public String chat(){StringBuilder b=new StringBuilder();Cursor c=query("SELECT kind,description FROM events WHERE kind IN ('USER_MESSAGE','MODEL_OUTPUT','ERROR') ORDER BY id ASC LIMIT 120",null);while(c.moveToNext())b.append("USER_MESSAGE".equals(c.getString(0))?"\nВы: ":"\nGPT: ").append(c.getString(1)).append("\n");c.close();return b.length()==0?"Начните разговор.":b.toString();}
    public String recent(String table){StringBuilder b=new StringBuilder();String sql="experiences".equals(table)?"SELECT logical_id,experience_type,confidence,what_happened,what_worked,what_failed FROM experiences ORDER BY id DESC LIMIT 40":"sources".equals(table)?"SELECT logical_id,source_type,source_name,created_at FROM sources ORDER BY id DESC LIMIT 40":"tasks".equals(table)?"SELECT logical_id,title,status,priority,updated_at FROM tasks ORDER BY id DESC LIMIT 40":"SELECT logical_id,kind,title,content,claim_status,verification_status,confidence FROM memory_objects ORDER BY id DESC LIMIT 40";Cursor c=query(sql,null);while(c.moveToNext()){b.append("\n• ").append(c.getString(0));for(int i=1;i<c.getColumnCount();i++)b.append(" | ").append(c.getString(i));b.append("\n");}c.close();return b.length()==0?"Нет данных.":b.toString();}
}
